const GalleryActionTypes = {
  FETCH_GALLERY_REQUEST: "FETCH_GALLERY_REQUEST",
  FETCH_GALLERY_SUCCESS: "FETCH_GALLERY_SUCCESS",
  FETCH_GALLERY_FAILURE: "FETCH_GALLERY_FAILURE",

  FETCH_CATEGORY_REQUEST: "FETCH_CATEGORY_REQUEST",
  FETCH_CATEGORY_SUCCESS: "FETCH_CATEGORY_SUCCESS",
  FETCH_CATEGORY_FAILURE: "FETCH_CATEGORY_FAILURE",

  FETCH_ARTWORK_REQUEST: "FETCH_ARTWORK_REQUEST",
  FETCH_ARTWORK_SUCCESS: "FETCH_ARTWORK_SUCCESS",
  FETCH_ARTWORK_FAILURE: "FETCH_ARTWORK_FAILURE",

  RESET_GALLERY: "RESET_GALLERY",
};

export default GalleryActionTypes;
