version: "3"
services:
  nginx:
    container_name: porfolio_nginx_webserver
    restart: always
    image: "nginx"
    depends_on:
      - api
      - client
    build:
      # dockerfile: Dockerfile.dev
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"
    #   # added
    # networks:
    #   - app-network
    # volumes:
    #   - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    #   - ./nginx/:/etc/nginx/conf.d
  api:
    container_name: portfolio_api
    build:
      context: "./server"
      # target: production
      # dockerfile: Dockerfile
      # dockerfile: Dockerfile.dev
      dockerfile: Dockerfile
    volumes:
      - "/app/node_modules"
      - "./server:/app"
    environment:
      - API_KEY=${API_KEY}
      - AUTH_DOMAIN=${AUTH_DOMAIN}
      - PROJECT_ID=${PROJECT_ID}
      - STORAGE_BUCKET=${STORAGE_BUCKET}
      - MESSAGING_SENDER_ID=${MESSAGING_SENDER_ID}
      - APP_ID=${APP_ID}
      - MEASUREMENT_ID=${MEASUREMENT_ID}
      - NODEMAILER_USER=${NODEMAILER_USER}
      - NODEMAILER_PASS=${NODEMAILER_PASS}
      - MAILING_PROJECT_ID=${MAILING_PROJECT_ID}
      - MAILING_SENDER_EMAIL_ADDRESS=${MAILING_SENDER_EMAIL_ADDRESS}
      - MAILING_SERVICE_CLIENT_ID=${MAILING_SERVICE_CLIENT_ID}
      - MAILING_SERVICE_CLIENT_SECRET=${MAILING_SERVICE_CLIENT_SECRET}
      - MAILING_SERVICE_REFRESH_TOKEN=${MAILING_SERVICE_REFRESH_TOKEN}
      - MAILING_SERVICE_ACCESS_TOKEN=${MAILING_SERVICE_ACCESS_TOKEN}
      - MAILING_REDIRECT_URI=${MAILING_REDIRECT_URI}
  #     # aded
  #   networks:
  #     - app-network
  # # added
    ports:
      - "5000:5000"
  client:
    container_name: portfolio_client
    stdin_open: true
    build:
      context: "./client"
      # target: production
      # dockerfile: Dockerfile
      # dockerfile: Dockerfile.dev
      dockerfile: Dockerfile

    volumes:
      - "/app/node_modules"
      - "./client:/app"
    command: npm run start
    tty: true
    # # added
    ports:
      - "3000:3000"
# networks:
#   app-network:
#     driver: bridge